RDF Processing Update

diff --git a/.github/workflows/fetch_decorations.yml b/.github/workflows/fetch_decorations.yml
--- a/.github/workflows/fetch_decorations.yml
+++ b/.github/workflows/fetch_decorations.yml
@@ -67,7 +67,7 @@ jobs:
       - name: Fetch Decoration Images and Update Data
         run: |
           set -e
-          # set -x
+          set -o pipefail
           # Read decorations.json and process each decoration
           jq -c '.[]' decorations.json | while read -r decoration; do
             name=$(echo "$decoration" | jq -r '.name')
@@ -162,11 +162,13 @@ jobs:
               fi
 
               # Attempt to extract the full filename
-              echo "$rdfData" > temp.rdf
-              echo "Temp RDF: $(cat temp.rdf)"
-              tempFilename=$(xmlstarlet sel -N rdf="*" -N property="*" -t -v "//property:Has_appearance/@rdf:resource" temp.rdf)
-              echo "Temp filename: $tempFilename"
-              rm temp.rdf
+              tempFilename=$(echo "$rdfData" | xmlstarlet sel -N rdf="*" -N property="*" -t -v "//property:Has_appearance/@rdf:resource")
+              if [ $? -ne 0 ]; then
+                echo "Error processing RDF data with xmlstarlet for decoration $name"
+                # Append the decoration as is to the updated file
+                echo "$decoration" >> decorations_updated.json
+                continue
+              fi
 
               # Check if a valid filename was found
               if [ -n "$tempFilename" ]; then
